apiVersion: v1
kind: Service
metadata:
  name: aws-example-octodex
spec:
  type: NodePort
  ports:
    - nodePort: 31479
      port: 8080
      targetPort: 5000
  selector:
    app: aws-example-octodex
